object Versions {

    const val GRADLE_PLUGIN_VERSION = "7.0.0"
    const val KOTLIN_VERSION = "1.5.20"
    const val NAV_VERSION = "2.4.0-alpha06"
    const val FRAGMENT_VERSION = "1.4.0-alpha06"
    const val CORE_KTX_VERSION = "1.6.0"
    const val APP_COMPAT_VERSION = "1.3.1"
    const val MATERIAL_VERSION = "1.4.0"
    const val APOLLO_VERSION = "2.5.5"
    const val KOIN_VERSION = "3.0.1"
    const val COROUTINES_VERSION = "1.3.9"
    const val LOGGING_INTERCEPTOR_VERSION = "4.2.1"
    const val LIFCECYCLE_VIEWMODEL_VERSION = "2.2.0"
    const val MOCKK_VERSION = "1.11.0"
    const val COIL_VERSION = "1.3.2"
    const val LIFECYCLE_RUNTIME_KTX_VERSION = "2.4.0-alpha03"
    const val CONSTRAINT_LAYOUT_VERSION = "2.1.0"
    const val DATASTORE_PROTOBUF_PLUGIN_VERSION = "0.8.12"
    const val DATASTORE_PROTOBUF_VERSION = "3.10.0"
    const val DATASTORE_VERSION = "1.0.0-alpha08"
    const val PAGING_VERSION = "3.1.0-alpha03"
    const val JUNIT_VERSION = "5.7.2"
    const val EXT_JUNIT_VERSION = "1.1.3"
    const val ESPRESSO_VERSION = "3.1.0"
    const val TEST_RUNNER_VERSION = "1.1.0"
    const val TEST_CORE_VERSION = "1.1.0"
    const val GSON_VERSION = "2.8.5"
    const val RETROFIT2_VERSION = "2.9.0"
    const val RETROFIT2_CONVERTER_GSON_VERSION = "2.9.0"
    const val RETROFIT2_CONVERTER_SCALARS_VERSION = "2.9.0"
    const val OKHTTP3_LOGGING_INTERCEPTOR_VERSION = "4.9.3"
    const val PLAY_SERVICES_LOCATION_VERSION = "19.0.1"
}